### ISSUE TITLE
from utils import output_pointcloud ImportError: cannot import name 'output_pointcloud'

### ISSUE THREAD

**Issue by jqxxhznu** [sjtuytc/betapose#1]
Hello, I want to run your code. I met this problem.Can you tell me why?

**Comment by danieldimit** [comment]
I have the same problem

**Comment by danieldimit** [comment]
I think I fixed it:
in the utils/model.py

change this:
`from utils import output_pointcloud`
to this:
`from utils.utils import output_pointcloud`

**Comment by sjtuytc** [comment]
Thanks above.
