### ISSUE TITLE
How to prepare data

### ISSUE THREAD

**Issue by lh641446825** [sjtuytc/betapose#10]
Sorry for disturbance. Can you provide the file structure in './betapose/3_6Dpose_estimator/train_YOLO/scripts'?
In AlexeyAB/darknet the file structure is 
├── VOCdevkit
│   └── VOC2007
│       ├── Annotations
│       │   ├──.xml
│       │   └── .xml
│       ├── ImageSets
│       │   ├── Layout
│       │   ├── Main
│       │   │   ├── test.txt
│       │   │   ├── train.txt
│       │   │   └── val.txt
│       │   └── Segmentation
│       ├── JPEGImages
│       │   ├──.jpg
│       │   └──.jpg
│       └── labels
│           └── .txt
└── voc_label.py

but you hadn't provide the voc_label.py and `.xml`files

**Comment by sjtuytc** [comment]
basically you don't need those label files. You can save box annotations in a h5, or pickle file. That should work also.
