### ISSUE TITLE
Couldn't open file: data_linemod_gt/02/all.txt

### ISSUE THREAD

**Issue by lh641446825** [sjtuytc/betapose#11]
Sorry for bothering you. I run the file `gt_single_object.py` ,then create the folder `data_linemod_gt`, I run `train_single.sh`, then  I got the following information:

>Total BFLOPS 65.290 
Loading weights from darknet53.conv.74...
 seen 64 
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
 Couldn't open file: data_linemod_gt/02/all.txt

What should I do?

**Comment by sjtuytc** [comment]
the 02 sequence is actually a multiple object sequence, probably it's due to this issue

**Comment by helloyuning** [comment]
> Sorry for bothering you. I run the file `gt_single_object.py` ,then create the folder `data_linemod_gt`, I run `train_single.sh`, then I got the following information:
> 
> > Total BFLOPS 65.290
> > Loading weights from darknet53.conv.74...
> > seen 64
> > Done!
> > Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
> > Couldn't open file: data_linemod_gt/02/all.txt
> 
> What should I do?

Hello,
Did run this code successfully?
I load sixd data return a error when I get 'obj_bb' from 'gt.yml'.
If you solved this problem, can you give me some suggesions?
