### ISSUE TITLE
Cannot reproduce paper results

### ISSUE THREAD

**Issue by ls15dev** [sjtuytc/betapose#16]
Hi,

I tried to train your network on the Linemod Ape object (01). I followed every steps of your tutorial.
But when I run betapose_evaluate, I cannot find results as you mention in your paper, especially with ADD metric. 
Do you have pkl (output of train KPD) file on the Ape object so I can check if the problem come from my learning ?

Regards

**Comment by sjtuytc** [comment]
Can you give me more details? Note that we report a lower result in our paper in comparison to SOTA detection+kp regression methods. It should be straight forward to reproduce it. You could refer to me segmentation-driven repo to found a better version.

**Comment by helloyuning** [comment]
> Hi,
> 
> I tried to train your network on the Linemod Ape object (01). I followed every steps of your tutorial. But when I run betapose_evaluate, I cannot find results as you mention in your paper, especially with ADD metric. Do you have pkl (output of train KPD) file on the Ape object so I can check if the problem come from my learning ?
> 
> Regards

Hello, Can I ask you some questions about running this code?
I trying to run this code, but when I load sixd data from 'gt.yml', It returned a error. 
There is no item 'obj_bb', can you telled how did you sloved this problem?
