### ISSUE TITLE
how to select the most confident keypoint for pnp?

### ISSUE THREAD

**Issue by zhuyazhi** [sjtuytc/betapose#17]
"when on the Occlusion dataset we only keep l = 10 most confident keypoints and abandon other low-confident keypoints".
hi~ I wonder how you select the most 10 confident keypoint for pnp? what's the confidence based on ?
I can't find the relevant code, could you give me some help?
best wishes.

**Comment by sjtuytc** [comment]
confidences are defined by the values of kp heatmaps
