### ISSUE TITLE
No such file or directory: 'DATAROOT/kpmodels/obj_01.ply'

### ISSUE THREAD

**Issue by lh641446825** [sjtuytc/betapose#3]
```
Traceback (most recent call last):
  File "annotate_keypoint.py", line 360, in <module>
    bench = load_bench(sixd_base)
  File "annotate_keypoint.py", line 73, in load_bench
    bench.kpmodels['{:02d}'.format(ID)].load(os.path.join(base_path, 'kpmodels/' + name + '.ply'), scale=bench.scale_to_meters)
  File "/home/Workspace/Project/betapose/2_keypoint_annotator/utils/model.py", line 80, in load
    data = PlyData.read(path)
  File "/home/anaconda3/envs/pytorch/lib/python2.7/site-packages/plyfile.py", line 390, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File "/home/anaconda3/envs/pytorch/lib/python2.7/site-packages/plyfile.py", line 469, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
```
What is kpmodels？You just say 

> Only folders called models and test are needed. Put them in DATAROOT/models and DATAROOT/test

**Comment by danieldimit** [comment]
I'm not sure, but I've copied the contents of [this](https://github.com/sjtuytc/betapose/tree/master/1_keypoint_designator/assets/sifts) folder to DATAROOT/kpmodels as it contains precalculated sifts that are used in the "Ⅲ. Annotate Keypoints" step.

Let me know when you've reached step "Ⅴ. Evaluate". I got "Ⅴ. Evaluate" to run without any errors, but it seems like my YOLO detector doesn't detect anything, because I get no predictions.

**Comment by lh641446825** [comment]
> I'm not sure, but I've copied the contents of [this](https://github.com/sjtuytc/betapose/tree/master/1_keypoint_designator/assets/sifts) folder to DATAROOT/kpmodels as it contains precalculated sifts that are used in the "Ⅲ. Annotate Keypoints" step.
> 
> Let me know when you've reached step "Ⅴ. Evaluate". I got "Ⅴ. Evaluate" to run without any errors, but it seems like my YOLO detector doesn't detect anything, because I get no predictions.

Thank you, I copy the contents of this folder to DATAROOT/kpmodels, and rename the .ply files. It works. But I don't know how to prepare data as AlexeyAB/darknet's instructions in "Ⅳ. Training".

**Comment by lh641446825** [comment]
> I'm not sure, but I've copied the contents of [this](https://github.com/sjtuytc/betapose/tree/master/1_keypoint_designator/assets/sifts) folder to DATAROOT/kpmodels as it contains precalculated sifts that are used in the "Ⅲ. Annotate Keypoints" step.
> 
> Let me know when you've reached step "Ⅴ. Evaluate". I got "Ⅴ. Evaluate" to run without any errors, but it seems like my YOLO detector doesn't detect anything, because I get no predictions.

Can you tell me how to prepare data as AlexeyAB/darknet's instructions? I download the darknet'code, but the "README.md" in ./scripts folder just some website of dataset. I don't know how to prepare data as AlexeyAB/darknet's instructions. What steps I need to perform?
