### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../exp/coco/seq5_Nov_1_1'

### ISSUE THREAD

**Issue by jqxxhznu** [sjtuytc/betapose#5]
Ⅳ. Training
3.Train on Linemod dataset without DPG.
when i try `$ python src/train.py --trainBatch 28 --expID seq5_Nov_1_1 --optMethod adam`
i get this error
**FileNotFoundError: [Errno 2] No such file or directory: '../exp/coco/seq5_Nov_1_1'**

please tell me how to solve it ,thank you!

**Comment by sjtuytc** [comment]
just create such directory
