### ISSUE TITLE
No errors, but method doesn't detect any objects

### ISSUE THREAD

**Issue by danieldimit** [sjtuytc/betapose#7]
I am running everything on Windows and I've finally managed to get everything to run without errors. But I have the following problem when I run the betapose_evaluate.py, the method doesn't detect any objects in all images. I am almost sure the problem is in the first step (object detection with YOLO), because it is the one that detects the object.

Here is what I've done to create the yolo weights file:

1. I've compiled YOLO directly from its original [source](https://github.com/AlexeyAB/darknet), because I am on windows and the make step that you've described wouldn't have worked for me. This means I didn't use the contents of the train_YOLO folder at all.
2. I've then trained the network for the APE object from the LINEMOD dataset. I've trained it with 2000 iterations
3. I've tested the weights with the YOLO program compiled in step 1) and it worked fine - it detected objects as expected.

BUT when I use the weight file in the betapose_evaluate.py it doesn't work. Can you tell me if you have made any major changes in the darknet code(train_YOLO)? Is my problem that I haven't used a darknet built from the train_YOLO folder? Here is a link to my weights for the APE object from the LINEMOD dataset - https://www.dropbox.com/s/2e3xdshsavp3t5a/01.weights?dl=0 and here is an example image with an APE in it - https://www.dropbox.com/s/rhar1p251dp4z31/000002.jpg?dl=0

P.S. Could you also recommend an open-sourced method for synthetic dataset generation?

**Comment by danieldimit** [comment]
Ok I installed ubuntu and trained the network on it via darknet compiled from the train_YOLO folder. Now the method does create an output.

**Comment by helloyuning** [comment]
> Ok I installed ubuntu and trained the network on it via darknet compiled from the train_YOLO folder. Now the method does create an output.

Hello, danieldimit.
I want run this code.
But the dataset link is not working in original repository, can you give me some suggestions? Or can I download the datset from anywhere?

Thanks
