### ISSUE TITLE
one image inference

### ISSUE THREAD

**Issue by mht1421** [sjtuytc/betapose#8]
Hi, 
I would like to take an image, forward it after the training and show results on the original image. 
what are the functions that apply the different transformations to the input image to make inference? and how can i return to the original image and project results on it?

**Comment by danieldimit** [comment]
+1

**Comment by sjtuytc** [comment]
We have not provided the visualization codes which are used in our paper. However, you can easilly make one by your self knowing a little bit about rendering techniques. As we have provided the evaluation code which computed the transformation matrix, you only needs to apply it to the model and render it on the image.

**Comment by danieldimit** [comment]
@mht1421 if you are still interested I've created a simple program that calculates the projection pixels of the object bounding box and paints them in red: 
https://github.com/danieldimit/project-ply-via-R-t-to-image
