### ISSUE TITLE
I met a problem

### ISSUE THREAD

**Issue by ldd071** [sjtuytc/betapose#9]
`Scanning dependencies of target pcl-sift
[ 50%] Building CXX object CMakeFiles/pcl-sift.dir/main.cpp.o
[100%] Linking CXX executable pcl-sift
/usr/bin/ld: warning: libboost_system.so.1.58.0, needed by /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libpcl_common.so, may conflict with libboost_system.so.1.60.0
/usr/bin/ld: warning: libboost_thread.so.1.58.0, needed by /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libpcl_common.so, may conflict with libboost_thread.so.1.60.0
/usr/bin/ld: warning: libboost_filesystem.so.1.58.0, needed by /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libpcl_io.so, may conflict with libboost_filesystem.so.1.60.0
/usr/bin/ld: warning: libboost_iostreams.so.1.58.0, needed by /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libpcl_io.so, may conflict with libboost_iostreams.so.1.60.0
/usr/bin/ld: warning: libboost_chrono.so.1.58.0, needed by /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libpcl_io.so, may conflict with libboost_chrono.so.1.60.0
CMakeFiles/pcl-sift.dir/main.cpp.o：在函数‘main’中：
/home/panxiang/ldd/betapose-master/1_keypoint_designator/main.cpp:93：对‘pcl::visualization::PCLVisualizer::PCLVisualizer(std::string const&, bool)’未定义的引用
/home/panxiang/ldd/betapose-master/1_keypoint_designator/main.cpp:101：对‘pcl::visualization::PCLVisualizer::setPointCloudRenderingProperties(int, double, std::string const&, int)’未定义的引用
CMakeFiles/pcl-sift.dir/main.cpp.o：在函数‘pcl::PLYWriter::write(std::string const&, pcl::PCLPointCloud2 const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool)’中：
/usr/include/pcl-1.7/pcl/io/ply_io.h:630：对‘pcl::PLYWriter::writeBinary(std::string const&, pcl::PCLPointCloud2 const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool)’未定义的引用
/usr/include/pcl-1.7/pcl/io/ply_io.h:632：对‘pcl::PLYWriter::writeASCII(std::string const&, pcl::PCLPointCloud2 const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, int, bool)’未定义的引用
CMakeFiles/pcl-sift.dir/main.cpp.o：在函数‘pcl::PLYWriter::write(std::string const&, pcl::PCLPointCloud2 const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool, bool)’中：
/usr/include/pcl-1.7/pcl/io/ply_io.h:653：对‘pcl::PLYWriter::writeBinary(std::string const&, pcl::PCLPointCloud2 const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool)’未定义的引用
/usr/include/pcl-1.7/pcl/io/ply_io.h:655：对‘pcl::PLYWriter::writeASCII(std::string const&, pcl::PCLPointCloud2 const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, int, bool)’未定义的引用
CMakeFiles/pcl-sift.dir/main.cpp.o：在函数‘pcl::search::OrganizedNeighbor<pcl::PointXYZ>::OrganizedNeighbor(bool, float, unsigned int)’中：
/usr/include/pcl-1.7/pcl/search/organized.h:95：对‘pcl::search::Search<pcl::PointXYZ>::Search(std::string const&, bool)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/pcl-sift.dir/build.make:352: recipe for target 'pcl-sift' failed
make[2]: *** [pcl-sift] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/pcl-sift.dir/all' failed
make[1]: *** [CMakeFiles/pcl-sift.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
build_and_run.sh: 5: build_and_run.sh: ./pcl-sift: not found
**I have encountered this problem, how can I solve it?`**

**Comment by sjtuytc** [comment]
this code is from Github, you could try to search it or find another code to abstract SIFT points.
